# locks:
#   - name    : emergency_lock
#     topic   : /emergency_lock_trigger
#     timeout : 0.0
#     priority: 200

#   - name    : teleop_lock
#     topic   : /emergency_lock_trigger
#     timeout : 0.0
#     priority: 50

# topics:
#   - name    : emergency_stop
#     topic   : /emergency_cmd_vel
#     timeout : 0.5
#     priority: 250

#   - name    : remote
#     topic   : /remote_cmd_vel
#     timeout : 0.5
#     priority: 80

#   - name    : teleop
#     topic   : /teleop_cmd_vel
#     timeout : 0.5
#     priority: 10

locks: []

topics:
  - name    : emergency_stop
    topic   : /emergency_cmd_vel
    timeout : 0.5
    priority: 100
  
  - name    : mux_output
    topic   : /cmd_vel  # mux 的输出话题
    timeout : 0.5
    priority: 50  # 低于紧急停止